"""Add teacher id 

Revision ID: ee5a6fb22040
Revises: 99a921ef1fa6
Create Date: 2025-08-29 17:04:39.354763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5a6fb22040'
down_revision: Union[str, Sequence[str], None] = '99a921ef1fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('teacher_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'teacher_id')
    # ### end Alembic commands ###
