"""Change to subject 

Revision ID: b9f0bbf86bfc
Revises: 0353deb0c944
Create Date: 2025-09-06 14:05:23.818569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f0bbf86bfc'
down_revision: Union[str, Sequence[str], None] = '0353deb0c944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizs', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_quizs_question_id_questions'), 'quizs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizs_subject_id_subjects'), 'quizs', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quizs', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizs', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_quizs_subject_id_subjects'), 'quizs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizs_question_id_questions'), 'quizs', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quizs', 'subject_id')
    # ### end Alembic commands ###
