"""Add lister events

Revision ID: 746c67a6b6c6
Revises: e6ff53e0cb00
Create Date: 2025-09-09 14:25:06.774798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746c67a6b6c6'
down_revision: Union[str, Sequence[str], None] = 'e6ff53e0cb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizs', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizs', 'end_time')
    # ### end Alembic commands ###
