"""Change structure

Revision ID: 99eeaba92518
Revises: ee5a6fb22040
Create Date: 2025-09-05 14:14:03.337430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99eeaba92518'
down_revision: Union[str, Sequence[str], None] = 'ee5a6fb22040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'teacher_id')
    op.add_column('quizs', sa.Column('question_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_quizs_subject_id_subjects'), 'quizs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizs_question_id_questions'), 'quizs', 'questions', ['question_id'], ['id'])
    op.drop_column('quizs', 'subject_id')
    op.drop_column('quizs', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizs', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quizs', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_quizs_question_id_questions'), 'quizs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizs_subject_id_subjects'), 'quizs', 'subjects', ['subject_id'], ['id'])
    op.drop_column('quizs', 'question_id')
    op.add_column('questions', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
