"""Change quiz

Revision ID: 920713638cf7
Revises: 5315a8d78a6e
Create Date: 2025-11-03 11:14:43.270212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920713638cf7'
down_revision: Union[str, Sequence[str], None] = '5315a8d78a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('quiz_name', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('quizzes', sa.Column('group_id', sa.Integer(), nullable=False))
    op.drop_column('quizzes', 'subject_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('quizzes', 'group_id')
    op.drop_column('quizzes', 'user_id')
    op.drop_column('quizzes', 'quiz_name')
    # ### end Alembic commands ###
