"""Add auto delete

Revision ID: da102c62075a
Revises: 99eeaba92518
Create Date: 2025-09-05 14:27:15.282207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da102c62075a'
down_revision: Union[str, Sequence[str], None] = '99eeaba92518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_questions_subject_id_subjects'), 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_questions_subject_id_subjects'), 'questions', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_quizs_question_id_questions'), 'quizs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizs_question_id_questions'), 'quizs', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_results_quiz_id_quizs'), 'results', type_='foreignkey')
    op.create_foreign_key(op.f('fk_results_quiz_id_quizs'), 'results', 'quizs', ['quiz_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_results_quiz_id_quizs'), 'results', type_='foreignkey')
    op.create_foreign_key(op.f('fk_results_quiz_id_quizs'), 'results', 'quizs', ['quiz_id'], ['id'])
    op.drop_constraint(op.f('fk_quizs_question_id_questions'), 'quizs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizs_question_id_questions'), 'quizs', 'questions', ['question_id'], ['id'])
    op.drop_constraint(op.f('fk_questions_subject_id_subjects'), 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_questions_subject_id_subjects'), 'questions', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###
