"""Add quiz question

Revision ID: 1205b6504428
Revises: 429153831b2c
Create Date: 2025-11-03 16:02:22.666786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1205b6504428'
down_revision: Union[str, Sequence[str], None] = '429153831b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quizzes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quizzes', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quizzes', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quizzes', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quizzes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
