"""Add teacher_id to subject

Revision ID: 0353deb0c944
Revises: da102c62075a
Create Date: 2025-09-05 14:31:23.522917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0353deb0c944'
down_revision: Union[str, Sequence[str], None] = 'da102c62075a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('teacher_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'teacher_id')
    # ### end Alembic commands ###
