"""Add RBAC

Revision ID: a6fca41cee57
Revises: 6be06cedb1a9
Create Date: 2025-09-29 08:22:39.064381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6fca41cee57'
down_revision: Union[str, Sequence[str], None] = '6be06cedb1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('results', 'start_time')
    op.drop_column('results', 'end_time')
    op.alter_column('subjects', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('results', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('results', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
