"""Delete quiz_question

Revision ID: 5315a8d78a6e
Revises: 44aaa0bd2478
Create Date: 2025-10-30 14:08:21.357522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5315a8d78a6e'
down_revision: Union[str, Sequence[str], None] = '44aaa0bd2478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_quizzes')
    op.add_column('quizzes', sa.Column('subject_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'subject_id')
    op.create_table('question_quizzes',
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_quizzes_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_question_quizzes_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_quizzes'))
    )
    # ### end Alembic commands ###
