"""Add quiz to status 

Revision ID: 86efa9404a4a
Revises: b9f0bbf86bfc
Create Date: 2025-09-08 15:53:46.279658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86efa9404a4a'
down_revision: Union[str, Sequence[str], None] = 'b9f0bbf86bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizs', sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'FINISHED', name='quizstatus', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizs', 'status')
    # ### end Alembic commands ###
