"""Delete subject

Revision ID: 44aaa0bd2478
Revises: a6fca41cee57
Create Date: 2025-10-30 13:40:47.677760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44aaa0bd2478'
down_revision: Union[str, Sequence[str], None] = 'a6fca41cee57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1️⃣ Drop foreign key constraints that depend on subjects or quizs
    op.drop_constraint(op.f('fk_questions_subject_id_subjects'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_results_quiz_id_quizs'), 'results', type_='foreignkey')

    # 2️⃣ Now it’s safe to drop old tables
    op.drop_table('quizs')
    op.drop_table('subjects')

    # 3️⃣ Create new tables
    op.create_table(
        'quizzes',
        sa.Column('question_number', sa.Integer(), nullable=False),
        sa.Column('quiz_time', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=False),
        sa.Column('quiz_pin', sa.String(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'FINISHED', name='quizstatus', native_enum=False),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes')),
        sa.UniqueConstraint('quiz_pin', name=op.f('uq_quizzes_quiz_pin')),
    )

    op.create_table(
        'question_quizzes',
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('quiz_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_quizzes_question_id_questions'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_question_quizzes_quiz_id_quizzes'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_question_quizzes')),
    )

    # 4️⃣ Alter columns after the dependent drops
    op.alter_column('questions', 'text', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('questions', 'option_a', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('questions', 'option_b', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('questions', 'option_c', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('questions', 'option_d', existing_type=sa.VARCHAR(), nullable=False)

    # 5️⃣ Drop old image columns
    op.drop_column('questions', 'option_d_image')
    op.drop_column('questions', 'option_b_image')
    op.drop_column('questions', 'option_a_image')
    op.drop_column('questions', 'image')
    op.drop_column('questions', 'option_c_image')

    # 6️⃣ Add new foreign key for results → quizzes
    op.create_foreign_key(op.f('fk_results_quiz_id_quizzes'), 'results', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_results_quiz_id_quizzes'), 'results', type_='foreignkey')
    op.create_foreign_key(op.f('fk_results_quiz_id_quizs'), 'results', 'quizs', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.add_column('questions', sa.Column('option_c_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('option_a_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('option_b_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('option_d_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_questions_subject_id_subjects'), 'questions', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('questions', 'option_d',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'option_c',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'option_b',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'option_a',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('quizs',
    sa.Column('question_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('quiz_pin', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_quizs_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizs'))
    )
    op.create_table('subjects',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    op.drop_table('question_quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
