"""Add quiz question

Revision ID: 6faea9460dfc
Revises: 920713638cf7
Create Date: 2025-11-03 14:46:35.349654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6faea9460dfc'
down_revision: Union[str, Sequence[str], None] = '920713638cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_quiz',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_quiz_question_id_questions')),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_question_quiz_quiz_id_quizzes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_quiz'))
    )
    op.add_column('questions', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'user_id')
    op.drop_table('question_quiz')
    # ### end Alembic commands ###
