"""Change to faculty nulable

Revision ID: 4c7b38dbba96
Revises: 25d249f2bbdf
Create Date: 2025-09-03 11:40:17.938848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7b38dbba96'
down_revision: Union[str, Sequence[str], None] = '25d249f2bbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'faculty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'faculty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
