"""Add some changes

Revision ID: 68787d334e50
Revises: d956ded4227d
Create Date: 2025-09-04 12:05:50.851472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68787d334e50'
down_revision: Union[str, Sequence[str], None] = 'd956ded4227d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_students_user_id'), 'students', ['user_id'])
    op.drop_constraint(op.f('fk_students_user_id_users'), 'students', type_='foreignkey')
    op.create_foreign_key(op.f('fk_students_user_id_users'), 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_teachers_user_id'), 'teachers', ['user_id'])
    op.drop_constraint(op.f('fk_teachers_user_id_users'), 'teachers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teachers_user_id_users'), 'teachers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_workers_user_id'), 'workers', ['user_id'])
    op.drop_constraint(op.f('fk_workers_user_id_users'), 'workers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workers_user_id_users'), 'workers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workers_user_id_users'), 'workers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workers_user_id_users'), 'workers', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('uq_workers_user_id'), 'workers', type_='unique')
    op.drop_constraint(op.f('fk_teachers_user_id_users'), 'teachers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teachers_user_id_users'), 'teachers', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('uq_teachers_user_id'), 'teachers', type_='unique')
    op.drop_constraint(op.f('fk_students_user_id_users'), 'students', type_='foreignkey')
    op.create_foreign_key(op.f('fk_students_user_id_users'), 'students', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('uq_students_user_id'), 'students', type_='unique')
    # ### end Alembic commands ###
