"""Correct quiz

Revision ID: 342c0ead91d7
Revises: 53b579de9099
Create Date: 2025-11-06 10:28:38.680974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342c0ead91d7'
down_revision: Union[str, Sequence[str], None] = '53b579de9099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_question_quiz_quiz_id_quizzes'), 'question_quiz', type_='foreignkey')
    op.drop_constraint(op.f('fk_question_quiz_question_id_questions'), 'question_quiz', type_='foreignkey')
    op.create_foreign_key(op.f('fk_question_quiz_quiz_id_quizzes'), 'question_quiz', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_question_quiz_question_id_questions'), 'question_quiz', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_question_quiz_question_id_questions'), 'question_quiz', type_='foreignkey')
    op.drop_constraint(op.f('fk_question_quiz_quiz_id_quizzes'), 'question_quiz', type_='foreignkey')
    op.create_foreign_key(op.f('fk_question_quiz_question_id_questions'), 'question_quiz', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('fk_question_quiz_quiz_id_quizzes'), 'question_quiz', 'quizzes', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
