"""Changed tasks table

Revision ID: 7e571b650908
Revises: 9db1107455a3
Create Date: 2025-11-11 08:35:57.722700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e571b650908'
down_revision: Union[str, Sequence[str], None] = '9db1107455a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('is_activate', sa.Boolean(), nullable=False))
    op.drop_column('quizzes', 'status')
    op.drop_column('quizzes', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('quizzes', sa.Column('status', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
    op.drop_column('quizzes', 'is_activate')
    # ### end Alembic commands ###
