"""Changed tasks table

Revision ID: acc5c0c6f332
Revises: 0e5ad9bb6f5e
Create Date: 2025-11-11 18:40:27.545297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc5c0c6f332'
down_revision: Union[str, Sequence[str], None] = '0e5ad9bb6f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'is_activate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'is_activate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
