"""Add user id in user

Revision ID: 5de6f561949f
Revises: d773f3093547
Create Date: 2025-09-02 17:00:51.128276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de6f561949f'
down_revision: Union[str, Sequence[str], None] = 'd773f3093547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_groups_chair_id_chairs'), 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_groups_faculty_id_facultys'), 'groups', 'facultys', ['faculty_id'], ['id'], ondelete='CASCADE')
    op.drop_column('groups', 'chair_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('chair_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_groups_faculty_id_facultys'), 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_groups_chair_id_chairs'), 'groups', 'chairs', ['chair_id'], ['id'], ondelete='CASCADE')
    op.drop_column('groups', 'faculty_id')
    # ### end Alembic commands ###
