"""add department_id to workers

Revision ID: d2955b8b882b
Revises: 7ba4e6f6218d
Create Date: 2025-08-31 12:39:43.199243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2955b8b882b'
down_revision: Union[str, Sequence[str], None] = '7ba4e6f6218d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_workers_department_id_departments'), 'workers', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workers_department_id_departments'), 'workers', type_='foreignkey')
    op.drop_column('workers', 'department_id')
    # ### end Alembic commands ###
