"""Changed tasks table

Revision ID: 56a585838afe
Revises: 7a1219141074
Create Date: 2025-11-11 18:49:49.938700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a585838afe'
down_revision: Union[str, Sequence[str], None] = '7a1219141074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE quizzes SET is_activate = false WHERE is_activate IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'is_activate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text("false")
               )
    

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'is_activate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
