"""Correct quiz

Revision ID: 53b579de9099
Revises: eafbe0a800b1
Create Date: 2025-11-05 21:59:12.597277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b579de9099'
down_revision: Union[str, Sequence[str], None] = 'eafbe0a800b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_quizzes_quiz_pin'), 'quizzes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_quizzes_quiz_pin'), 'quizzes', ['quiz_pin'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
