"""Add user id in user

Revision ID: d773f3093547
Revises: 4418dcaf6fda
Create Date: 2025-09-02 15:48:17.229841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd773f3093547'
down_revision: Union[str, Sequence[str], None] = '4418dcaf6fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_students_user_id_users'), 'students', 'users', ['user_id'], ['id'])
    op.add_column('teachers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_teachers_user_id_users'), 'teachers', 'users', ['user_id'], ['id'])
    op.add_column('workers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_workers_user_id_users'), 'workers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workers_user_id_users'), 'workers', type_='foreignkey')
    op.drop_column('workers', 'user_id')
    op.drop_constraint(op.f('fk_teachers_user_id_users'), 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'user_id')
    op.drop_constraint(op.f('fk_students_user_id_users'), 'students', type_='foreignkey')
    op.drop_column('students', 'user_id')
    # ### end Alembic commands ###
