"""Add cascade

Revision ID: 4418dcaf6fda
Revises: 8c9dea7358b7
Create Date: 2025-08-31 14:22:46.015395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4418dcaf6fda'
down_revision: Union[str, Sequence[str], None] = '8c9dea7358b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chairs_faculty_id_facultys'), 'chairs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chairs_faculty_id_facultys'), 'chairs', 'facultys', ['faculty_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_groups_chair_id_chairs'), 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_groups_chair_id_chairs'), 'groups', 'chairs', ['chair_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_students_group_id_groups'), 'students', type_='foreignkey')
    op.create_foreign_key(op.f('fk_students_group_id_groups'), 'students', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_teachers_chair_id_chairs'), 'teachers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teachers_chair_id_chairs'), 'teachers', 'chairs', ['chair_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_workers_department_id_departments'), 'workers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workers_department_id_departments'), 'workers', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workers_department_id_departments'), 'workers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workers_department_id_departments'), 'workers', 'departments', ['department_id'], ['id'])
    op.drop_constraint(op.f('fk_teachers_chair_id_chairs'), 'teachers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teachers_chair_id_chairs'), 'teachers', 'chairs', ['chair_id'], ['id'])
    op.drop_constraint(op.f('fk_students_group_id_groups'), 'students', type_='foreignkey')
    op.create_foreign_key(op.f('fk_students_group_id_groups'), 'students', 'groups', ['group_id'], ['id'])
    op.drop_constraint(op.f('fk_groups_chair_id_chairs'), 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_groups_chair_id_chairs'), 'groups', 'chairs', ['chair_id'], ['id'])
    op.drop_constraint(op.f('fk_chairs_faculty_id_facultys'), 'chairs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chairs_faculty_id_facultys'), 'chairs', 'facultys', ['faculty_id'], ['id'])
    # ### end Alembic commands ###
